### ISSUE TITLE
Visual Memory Editing Info

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#292]
Improve convention for engaging with a memory, entry, etc.

- [x] visual indicator that should pop up as a line identifying item above member system chat
  - different gray or maroon?color, thin one-line of text, begins: Active Memory: `title`
  - clicking on bar forces open the summary info
  - has close button to `deactivate memory`
  - currently only one memory active at a time, but later can combine
  - could also be a rotary that scrolls through memories including add
- [x] `mylife-avatar.mjs` align `shadow()` and `chatRequest()`
- [x] API interpretation: text parser with active memory, can fire, also could ask if familiar with memory #xxx and if not, send current summary, this might be more interesting mechanic?

**Comment by Mookse** [comment]
- [x] institute html active memory bar
- [x] create base css classes
- [x] assign listeners; ended up on setActiveItem
  - [x] close [close and deactivate memory]
  - [x] bar [open memory item popup]
  - [x] title [change title?]
- [x] on scrapbook fire setActiveItem
  - [x] `bots.mjs`
  - [x] `members.mjs`
- [x] Chat should inspect Active Chat variables instead of shadow, and send ID as before [a little more complicated, as there were two different mechanics, and the shadow version was the more advanced
- [x] investigation: how is proxy data used on backend; confirm against addition of variables from new location and use of `proxy` field itself
- [x] Fix Shadows (they no longer need to do "anything" but focus window and prepopulate text); store shadow clicks in Active Chat, but **expect** that this will change, that it will be dynamic inside of chat area and not summary area.
  - [x] convert `seedInput` to use active chat for dataset
  - [x] payload: `{ action, botId, itemId, message, role, shadowId, }`
  - [x] `functions.mjs` remove `/shadow` endpoint, route logic to `chat()`
  - [x] `mylife-avatar.mjs` remove `shadow()` function and convert to chat
  - [x] frontend shadows are not removed after submission, and itemId should always default to just the `guid`, ergo delete sympathetic code inside of `bots.mjs`

**Comment by Mookse** [comment]
base classes for active chat content

``` css

.chat-active-items {
	align-items: center;
	display: flex;
	flex: 1 0 auto;
	flex-direction: column;
	padding-left: 3rem;
	margin-bottom: 0.5rem;
	max-width: 100%;
}
.chat-active-item {
	background-color: #007BFF;
	border: solid thin aliceblue;
	border-radius: 0.6rem;
	display: flex;
	flex: 1 0 auto;
    flex-direction: row;
    padding: 0.3rem;
    width: 100%;
}
.chat-active-item-close {
	align-self: top;
	color: maroon;
	cursor: pointer;
	font-size: 1.25rem;
	margin-left: 2rem;
}
.chat-active-item-icon {
	color: #e9eb5c;
	font-size: 1.25rem;
	margin-right: 0.5em;
}
.chat-active-item-text {
    color: aliceblue;
    display: flex;
    flex: 1 0 auto;
    max-width: 80%;
}
.chat-member-container,
.chat-user-container {
	display: flex;
	flex-direction: row;
	width: 100%;
}
```
